name: archinstall Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint archinstall.sh
        run: shellcheck src/archinstall.sh

  json-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validate user_config.json
        run: jq . config/user_config.json

  dry-run:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm jq gptfdisk btrfs-progs reflector sudo
          yes | pacman -Scc

      - name: Dry-run config load
        run: |
          bash -n src/archinstall.sh
          jq . config/user_config.json